general.import=["~/.config/alacritty/argonaut.toml"]
[env]
TERM = "xterm-256color"
[window]
padding = {x=2,y=2}
dynamic_padding = true
opacity = 0.85
[window.dimensions]
columns = 75
lines = 21
[font]
normal = { family = "Martian Mono Nerd Font", style = "Regular" }
bold = { family = "Martian Mono Nerd Font", style = "Bold" }
italic = { family = "Martian Mono Nerd Font", style = "Italic" }
bold_italic = { family = "Martian Mono Nerd Font", style = "Bold Italic" }
size = 14

[cursor]
style = {shape = "Beam"}
