general.import=["~/.config/alacritty/themes/ostuxcat.toml"]
[env]
TERM = "rxvt"
[window]
padding = {x=3,y=3}
opacity = 0.98
title = "ostuxcat"
dynamic_title = false
[window.dimensions]
columns = 75
lines = 21
[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 15

[cursor]
style = {shape = "Beam"}
